version: '3.8'


services:
  bank_nginx:
    build:
      context: Nginx
      dockerfile: Dockerfile
    ports:
      - "8070:80"
    depends_on:
      - bank_fronted
  bank_fronted:
    container_name: bank_fronted
    build:
      context: Frontend
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - bank_server
  bank_server:
    container_name: bank_server
    build:
      context: Server
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - bank_db
  bank_db:
    container_name: bank_db
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Sqlhaslo123$"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Evaluation"
    volumes:
      - bank-db:/var/lib/mssql

volumes:
  bank-db:
    driver: local