version: '3.8'


services:
  bank-nginx:
    build:
      context: Nginx
      dockerfile: Dockerfile
    ports:
      - "8070:80"
      - "443:443"
    depends_on:
      - bank-frontend
  bank-frontend:
    container_name: bank-frontend
    build:
      context: Frontend/Server
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - bank-server
  bank-server:
    container_name: bank-server
    build:
      context: Server
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - bank-db
  bank-db:
    container_name: bank_db
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1433:1433"
    env_file:
      - .env
    volumes:
      - bank-db:/var/lib/mssql

volumes:
  bank-db:
    driver: local