version: '3.8'


services:
  bank-nginx:
    build:
      context: Nginx
      dockerfile: Dockerfile
    ports:
      - "8070:80"
    depends_on:
      - bank-client
  bank-client:
    build:
      context: Client
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - bank-server
  bank-server:
    build:
      context: Server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - bank-db
  bank-db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Sqlhaslo123$"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Evaluation"
    volumes:
      - bank-db:/var/lib/mssql

volumes:
  bank-db:
    driver: local